-- =============================================================================
-- AI Person in a Box: Belief Pipeline Tables
-- PostgreSQL 16
--
-- The belief pipeline is how the entity converts raw observation (NoSQL,
-- high-dimensional) into structured knowledge (SQL, low-dimensional).
--
-- Three stages:
--
--   1. observations_nosql_index  — lightweight pointer table. The actual
--      observation data lives in MongoDB; this table lets the Executive
--      Module query for observations by type, time, and sensor without
--      loading the full documents.
--
--   2. candidate_beliefs         — tentative patterns under evaluation.
--      "I think I see something, but I haven't verified it yet."
--      The entity can act on candidates (with reduced confidence scoring)
--      but marks them as provisional.
--
--   3. committed_beliefs         — verified patterns promoted from candidates.
--      These are stored in the ontology tables (entities, transformations,
--      joins) but this table tracks their epistemic history: where they came
--      from, how confident, when they were last tested.
--
-- The dimensional collapse happens at the candidate→committed boundary.
-- A candidate may reference dozens of NoSQL observations. The committed
-- belief distills these into a handful of structured attributes.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- OBSERVATIONS INDEX
-- Mirrors MongoDB so the Executive Module can find relevant observations
-- using SQL joins without loading full documents.
-- -----------------------------------------------------------------------------
CREATE TABLE observations_index (
    id              SERIAL PRIMARY KEY,
    -- The MongoDB document ID for the full observation
    nosql_doc_id    TEXT NOT NULL UNIQUE,
    -- When the observation was recorded
    observed_at     TIMESTAMPTZ NOT NULL,
    -- Source: sensor, log_event, interoception, llm_response, etc.
    source_type     VARCHAR(50) NOT NULL,
    source_id       TEXT,
    -- A low-dimensional summary for SQL querying
    summary         JSONB NOT NULL DEFAULT '{}',
    -- Tags for pattern-detection queries
    tags            TEXT[] NOT NULL DEFAULT '{}',
    -- Which candidate beliefs this observation has been assigned to
    candidate_ids   INTEGER[] NOT NULL DEFAULT '{}',
    indexed_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_obs_observed_at  ON observations_index(observed_at DESC);
CREATE INDEX idx_obs_source       ON observations_index(source_type, source_id);
CREATE INDEX idx_obs_summary      ON observations_index USING GIN(summary);
CREATE INDEX idx_obs_tags         ON observations_index USING GIN(tags);
CREATE INDEX idx_obs_candidates   ON observations_index USING GIN(candidate_ids);


-- -----------------------------------------------------------------------------
-- CANDIDATE BELIEFS
-- Patterns that have been noticed but not yet verified enough to commit.
-- The entity treats these as hypotheses: it may act on them, but with
-- lower confidence weighting and explicit marking as provisional.
--
-- Candidates are generated by the pattern detector, which queries the
-- NoSQL store for clusters of similar observations and asks the LLM
-- (at low temperature, encyclopedia mode) to propose a structured
-- description of the pattern.
-- -----------------------------------------------------------------------------
CREATE TABLE candidate_beliefs (
    id              SERIAL PRIMARY KEY,
    -- Human-readable identifier for tracking
    name            VARCHAR(255) NOT NULL,
    -- The proposed belief, expressed as a structured JSON claim
    claim           JSONB NOT NULL,
    -- Which observations support this candidate (observation IDs)
    supporting_obs  INTEGER[] NOT NULL DEFAULT '{}',
    -- Which observations contradict it
    contradicting_obs INTEGER[] NOT NULL DEFAULT '{}',
    -- Current confidence based on ratio of supporting to contradicting
    confidence      NUMERIC(4,3) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    -- How many times has this candidate been tested against new observations?
    test_count      INTEGER NOT NULL DEFAULT 0,
    -- What was the last test prediction, and did it come true?
    last_prediction JSONB,
    last_test_at    TIMESTAMPTZ,
    -- Threshold to meet before promotion to committed belief
    promotion_threshold NUMERIC(4,3) NOT NULL DEFAULT 0.75,
    -- Minimum number of confirming observations required
    min_observations INTEGER NOT NULL DEFAULT 5,
    -- Which LLM version generated the initial hypothesis
    llm_version     TEXT,
    -- Temperature used when this candidate was generated (high=imagination, low=reference)
    llm_temperature NUMERIC(3,2),
    -- Status in the pipeline
    status          VARCHAR(20) NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'promoted', 'rejected', 'suspended')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_candidates_confidence ON candidate_beliefs(confidence DESC);
CREATE INDEX idx_candidates_status     ON candidate_beliefs(status);
CREATE INDEX idx_candidates_claim      ON candidate_beliefs USING GIN(claim);
CREATE INDEX idx_candidates_obs        ON candidate_beliefs USING GIN(supporting_obs);


-- -----------------------------------------------------------------------------
-- COMMITTED BELIEFS REGISTRY
-- A record of every belief that has been promoted from candidate to committed.
-- The actual belief lives in the ontology tables (as an entity, transformation,
-- or join). This table tracks the epistemic provenance.
--
-- Why keep this separate from the ontology tables?
-- The ontology tables are for what the entity believes.
-- This table is for how the entity knows what it believes.
-- Epistemic responsibility requires both.
-- -----------------------------------------------------------------------------
CREATE TABLE committed_beliefs_registry (
    id                  SERIAL PRIMARY KEY,
    -- Link to the ontology table where this belief now lives
    ontology_table      VARCHAR(30) NOT NULL
                        CHECK (ontology_table IN ('entity_types','entities','transformation_types','transformations','join_types','joins')),
    ontology_id         INTEGER NOT NULL,
    -- The candidate it was promoted from
    candidate_belief_id INTEGER REFERENCES candidate_beliefs(id),
    -- The claim as it was at promotion time (snapshot)
    claim_at_promotion  JSONB NOT NULL,
    -- Confidence at promotion
    confidence_at_promotion NUMERIC(4,3) NOT NULL,
    -- Current confidence (updated as new observations come in)
    current_confidence  NUMERIC(4,3) NOT NULL,
    -- How many times has this belief been tested since promotion?
    post_promotion_tests INTEGER NOT NULL DEFAULT 0,
    -- Has this belief ever been contradicted?
    contradicted        BOOLEAN NOT NULL DEFAULT FALSE,
    -- If contradicted, what was the confidence impact?
    contradiction_log   JSONB,
    -- Which LLM version(s) were involved in forming this belief
    llm_versions        TEXT[] NOT NULL DEFAULT '{}',
    promoted_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_tested_at      TIMESTAMPTZ,
    -- If this belief was later revised or retracted
    status              VARCHAR(20) NOT NULL DEFAULT 'active'
                        CHECK (status IN ('active', 'revised', 'retracted'))
);

CREATE INDEX idx_committed_ontology ON committed_beliefs_registry(ontology_table, ontology_id);
CREATE INDEX idx_committed_status   ON committed_beliefs_registry(status);
CREATE INDEX idx_committed_confidence ON committed_beliefs_registry(current_confidence DESC);
CREATE INDEX idx_committed_contradicted ON committed_beliefs_registry(contradicted) WHERE contradicted = TRUE;


-- -----------------------------------------------------------------------------
-- PATTERN DETECTION QUEUE
-- Tasks queued for the pattern detector. When new observations are indexed,
-- or when enough time has passed, pattern detection jobs are queued here.
-- The Executive Module processes these between other activities.
-- -----------------------------------------------------------------------------
CREATE TABLE pattern_detection_queue (
    id              SERIAL PRIMARY KEY,
    queued_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- What kind of pattern to look for
    task_type       VARCHAR(50) NOT NULL,
    -- Parameters for this detection run (which observations, what time window, etc.)
    parameters      JSONB NOT NULL DEFAULT '{}',
    status          VARCHAR(20) NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'running', 'completed', 'failed')),
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    -- What the detector found (new candidate IDs or null)
    result          JSONB,
    error           TEXT
);

CREATE INDEX idx_queue_status ON pattern_detection_queue(status, queued_at);


-- =============================================================================
-- EXAMPLE QUERIES — showing how the Executive Module navigates the pipeline
-- =============================================================================

-- Q1: What candidates are ready for promotion?
-- SELECT * FROM candidate_beliefs
-- WHERE status = 'active'
--   AND confidence >= promotion_threshold
--   AND array_length(supporting_obs, 1) >= min_observations
-- ORDER BY confidence DESC;

-- Q2: Has this observation already been assigned to a candidate?
-- SELECT c.*
-- FROM candidate_beliefs c
-- WHERE $observation_id = ANY(c.supporting_obs)
--   AND c.status = 'active';

-- Q3: Which committed beliefs have been contradicted and need review?
-- SELECT cbr.*, e.name, e.data
-- FROM committed_beliefs_registry cbr
-- JOIN entities e ON cbr.ontology_table = 'entities' AND cbr.ontology_id = e.id
-- WHERE cbr.contradicted = TRUE
--   AND cbr.status = 'active'
-- ORDER BY cbr.current_confidence ASC;

-- Q4: What did the entity believe about entity X, and how confident was it?
-- SELECT e.name, e.data, cbr.current_confidence, cbr.promoted_at, cbr.llm_versions
-- FROM entities e
-- JOIN committed_beliefs_registry cbr ON cbr.ontology_table = 'entities' AND cbr.ontology_id = e.id
-- WHERE e.id = $entity_id;
